### ISSUE TITLE
Fix user created by

### ISSUE THREAD

**Issue by KIMB0** [KIMB0/LSD_frontend#17]
### Description
This will fix the "by" field in the object, the it will take the logged in user instead of "foo" all the time (which does that the user can't upload a story).

### Tasks
- [ ] **1t:** Create a localstorage method that saves the logged in user
- [ ] **0,5t:** Get the user on post item method

### Acceptance criterias
- [ ] I can create a story with the logged in user

### Definition of Done
- [ ] Tested
- [ ] Reviewed

**Comment by KIMB0** [comment]
Took **0,8t**.
