### ISSUE TITLE
Create selected story page

### ISSUE THREAD

**Issue by KIMB0** [KIMB0/LSD_frontend#24]
### Description
As a user I want to go to selected story page and post comments

### Tasks
- [x] **0,5t:** Create a new component
- [x] **1t:** Style page
- [x] **1t:** Create logic for page

### Acceptance criterias
- [x] I can read comments
- [x] I can post comments

### Definition of Done
- [x] Tested
- [ ] Reviewed
